target:
  _target_: models.lightningModel_T2P.TBIFormer
  input_dim: 128
  d_model: 128
  d_inner: 1024
  n_layers: 2
  n_head: 8
  d_k: 64
  d_v: 64
  dropout: 0.2
  device: 'cuda'
  kernel_size: ${kernel_size}
  d_traj_query: 128     # Need to match
  opt: 
    kernel_size: ${kernel_size}
    input_time: ${input_time}
    output_time: ${output_time}
    hivt_embed_dim: 128 # Need to match
    num_modes: ${num_modes}
    device: 'cuda'
    theta: 2000
    batch_size: ${batch_size}
    num_joints: ${num_joints}
    dataset: ${dataset}
    sampling_method: ${sampling_method}